name: Cypress Tests

on: 
    push:
    schedule:
    - cron: "0 2 * * 0-5"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run test 

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: result
          path: reports/

